### ISSUE TITLE
best emulator for bypass

### ISSUE THREAD

**Issue by Tanuj-kumar-102** [Ms-dev3/EmulatorDetectionByPass#3]
bro emulator konsa use karu

**Comment by Ms-dev3** [comment]
> bro emulator konsa use karu

Download android SDK from official side and then flow below 


-     Open the command prompt and change the directory where your sdk is placed D:\Softwares\Android\sdk\tools\bin>

-     Now add your avdmanager in this,now your full code is D:\Softwares\Android\sdk\tools\bin>avdmanager list avd

-     It will show you a list of emulator device that you have already created after few seconds

-     Now typecd..

-     And run your emulator with this cmd, Here my emulator name is Tablet_API_25 so I have typed this name after the -avd. D:\Softwares\Android\sdk\tools>emulator -avd Tablet_API_25
